name: MontrÃ©al 2027 build and deploy

on:
  pull_request:
    types: [closed]
    branches: ['develop']
  push:
    branches:
      - feature/initial-release
  workflow_dispatch:

jobs:
  deploy:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -euo pipefail
            echo "Changing to deploy path"
            cd ${{ vars.STG_DEPLOY_PATH }}
            echo "Setting proper permissions"
            chmod -R u+w web/sites/default
            echo "Pulling latest code"
            git pull

      - name: Backup Database
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -euo pipefail
            echo "Changing to deploy path"
            cd ${{ vars.STG_DEPLOY_PATH }}
            echo "Backing up database"
            drush sql:dump > "/var/www/db_backups/${{ vars.STG_BU_FILE_PREFIX }}.$(date +'%Y-%m-%d_%H:%M:%S').sql"

      - name: Install Composer Dependencies
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -euo pipefail
            echo "Changing to deploy path"
            cd ${{ vars.STG_DEPLOY_PATH }}
            echo "Installing composer dependencies"
            composer install

      - name: Install NPM Dependencies
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -euo pipefail
            echo "Changing to deploy path"
            cd ${{ vars.STG_DEPLOY_PATH }}
            echo "Installing npm dependencies"
            npm install

      - name: Build Assets
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -euo pipefail
            echo "Changing to deploy path"
            cd ${{ vars.STG_DEPLOY_PATH }}
            echo "Building assets"
            npm run build

      - name: Clean up node_modules
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -euo pipefail
            echo "Changing to deploy path"
            cd ${{ vars.STG_DEPLOY_PATH }}
            echo "Cleaning up node_modules"
            rm -rf node_modules
            git restore package-lock.json

      - name: Run Drush Commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -euo pipefail
            echo "Changing to deploy path"
            cd ${{ vars.STG_DEPLOY_PATH }}
            echo "Clearing Drupal cache"
            drush cr
            echo "Importing config"
            drush cim -y
            echo "Updating database"
            drush updb -y
            echo "Final cache clear"
            drush cr
